### PR TITLE
Add FOLDL and ITAKE

### PR DESCRIPTION
**Pull request by shamazmazum**
Hi. This PR adds FOLDL (left-associative reduce) for generators and ITAKE which acts like TAKE but returns a generator instead of a list. I also fixed signalling of condition in TAKE.

### CODE REVIEW

**Comment by BnMcGn** [comment]
Thanks for the contribution.

A couple of things:
I feel that your names are a little terse. I'd like something a little more descriptive.

How about:
foldl -> reduce-generator
itake -> take-as-generator

The other thing: could the initial value to foldl be supplied as an optional keyword argument? If we use :initial-value as the name, we'll be consistent with REDUCE.

Otherwise, looks good!

**Comment by shamazmazum** [comment]
Those names come from Haskell and Julia, but I don't mind renaming. Functions are renamed and `:initial-value` argument is added.

**Comment by shamazmazum** [comment]
All those corner cases (which `foldl` doesn't have ;) ):

~~~~
CL-USER> (snakes:reduce-generator
          (lambda (&rest args) (format t "Hello~%") (apply #'* args))
          (snakes:list->generator '()))
Hello
1
CL-USER> (snakes:reduce-generator
          (lambda (&rest args) (format t "Hello~%") (apply #'* args))
          (snakes:list->generator '()) :initial-value 2)
2
CL-USER> (snakes:reduce-generator
          (lambda (&rest args) (format t "Hello~%") (apply #'* args))
		(snakes:list->generator '(3)))
3
CL-USER> (snakes:reduce-generator
          (lambda (&rest args) (format t "Hello~%") (apply #'* args))
          (snakes:list->generator '(3)) :initial-value 7)
Hello
21
CL-USER>
~~~~

**Comment by shamazmazum** [comment]
Thanks!

**Pull request merged**
